# Configuration
SAMPLES = ["Diglossa_cyanea_161093", "Diglossa_cyanea_162560"]
REFERENCE = "genome/hemoglobin_references.fasta"

rule all:
    input:
        expand("results/filtered/{sample}.filtered.vcf.gz", sample=SAMPLES)

#################
# FASTP (cleaning reads)
#################
rule fastp:
    threads: 4
    resources:
        runtime=3600,
        mem_mb=4000
    conda:
        "envs/fastp.yaml"
    input:
        r1="data/{sample}_R1_001.fastq.gz",
        r2="data/{sample}_R2_001.fastq.gz"
    output:
        r1="results/clean/{sample}_R1.clean.fastq.gz",
        r2="results/clean/{sample}_R2.clean.fastq.gz"
    params:
        json="results/clean/{sample}.fastp.json",
        html="results/clean/{sample}.fastp.html"
    shell:
        """
        fastp \
        -i {input.r1} -I {input.r2} \
        -o {output.r1} -O {output.r2} \
        -j {params.json} -h {params.html}
        """

#################################
# INDEX REFERENCE
#################################
rule index_ref:
    input:
        REFERENCE
    output:
        fai=REFERENCE + ".fai"
    conda:
        "envs/align.yaml"
    shell:
        """
        samtools faidx {input}
        """

rule bwa_index:
    input:
        REFERENCE
    output:
        amb=REFERENCE + ".amb",
        ann=REFERENCE + ".ann",
        bwt=REFERENCE + ".bwt",
        pac=REFERENCE + ".pac",
        sa=REFERENCE + ".sa"
    conda:
        "envs/align.yaml"
    shell:
        """
        bwa index {input}
        """

#################################
# ALIGNMENT
#################################
rule align:
    threads: 8  # Increased for better performance with bwa mem
    resources:
        runtime=240,
        mem_mb=8000
    input:
        r1="results/clean/{sample}_R1.clean.fastq.gz",
        r2="results/clean/{sample}_R2.clean.fastq.gz",
        ref=REFERENCE
    output:
        "results/aligned/{sample}.sam"
    conda:
        "envs/align.yaml"
    shell:
        """
        bwa mem -t {threads} {input.ref} {input.r1} {input.r2} > {output}
        """

#################################
# SORT + INDEX BAM (combined)
#################################
rule process_bam:
    threads: 4
    resources:
        runtime=120,
        mem_mb=8000
    input:
        "results/aligned/{sample}.sam"
    output:
        bam="results/aligned/{sample}.sorted.bam",
        bai="results/aligned/{sample}.sorted.bam.bai"
    conda:
        "envs/align.yaml"
    shell:
        """
        samtools sort -@ {threads} -o {output.bam} {input}
        samtools index {output.bam}
        """

#################################
# VARIANT CALLING
#################################
rule call_variants:
    resources:
        runtime=1800,
        mem_mb=4000
    input:
        bam="results/aligned/{sample}.sorted.bam",
        bai="results/aligned/{sample}.sorted.bam.bai",
        ref=REFERENCE,
        fai=REFERENCE + ".fai"
    output:
        "results/vcf/{sample}.vcf.gz"
    params:
        tmpdir="tmp/bcftools/{sample}"
    conda:
        "envs/bcftools.yaml"
    shell:
        """
        mkdir -p {params.tmpdir}
        bcftools mpileup -f {input.ref} {input.bam} | \
        bcftools call -mv -Oz -o {output} --threads {threads}
        """

#################################
# FILTER VARIANTS
#################################
rule filter_variants:
    resources:
        runtime=1800,
        mem_mb=4000
    input:
        vcf="results/vcf/{sample}.vcf.gz"
    output:
        filtered="results/filtered/{sample}.filtered.vcf.gz"
    params:
        prefix=lambda wildcards: f"results/filtered/{wildcards.sample}.filtered"
    conda:
        "envs/vcftools.yaml"
    shell:
        """
        vcftools \
        --gzvcf {input.vcf} \
        --remove-indels \
        --minQ 40 \
        --mac 2 \
        --min-meanDP 10 \
        --recode \
        --recode-INFO-all \
        --out {params.prefix}
        
        mv {params.prefix}.recode.vcf {params.prefix}.vcf
        bgzip -f {params.prefix}.vcf
        """